### ISSUE TITLE
[Feature Request] Create a getSnapshotList

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/cloud-debug-proxy-common#15]
Currently getting a list of breakpoints requires calling get on all breakpoint ids.  In many cases I would like to have the whole list.

**Comment by eyqs** [comment]
I decided to only send breakpoint IDs because I only used the actual breakpoint information when the user clicks on a snapshot in the Snapshot Explorer. Could you give some other cases where having the whole list is useful?

**Comment by iantalarico** [comment]
In some cases we need to have more context before we show the breakpoint.  For example showing the file and line number instead of the snapshot id.

In general I think it's probably better to expose more information than less, I don't think any harm comes from exposing this information and it allows others to do more with the data.  Not all Snapshot Explorer for all IDEs may function the same.

**Comment by eyqs** [comment]
Resolved by #18.
